// Estimated timestamps for elena-demo-call.mp3 (8:10). Proportional allocation.
export type TranscriptMsg = { role: "agent" | "caller"; text: string; t: number };
export const CALL_DURATION = 490;
export const transcript: TranscriptMsg[] = [
  { role: "agent", t: 0.0, text: "Thank you for calling Sonoran Justice Injury Law. This is Elena. How can I help you today?" },
  { role: "caller", t: 10.3, text: "Hello?" },
  { role: "agent", t: 12.1, text: "Hi there, I'm here. How can I help you today?" },
  { role: "caller", t: 17.9, text: "I was in an accident. I'm looking for a lawyer." },
  { role: "agent", t: 23.9, text: "I'm sorry you were in an accident. I'm here to help. Can you tell me a bit about what happened?" },
  { role: "caller", t: 34.7, text: "Yeah. I was driving down the road on McDowell going west, and when I was approaching 35th Avenue I had green, but a car coming the opposite way hit me. He didn't realize he had a red, and it just crashed right into me and my door." },
  { role: "agent", t: 59.3, text: "I'm sorry that happened to you. That sounds really frightening. Before I ask a few questions, are you somewhere safe right now, and does anyone need emergency medical help?" },
  { role: "caller", t: 77.9, text: "Yeah, I'm safe now. Nobody here needs any emergency help." },
  { role: "agent", t: 84.9, text: "I'm glad you're safe. I'm going to ask you a few questions so we can get the details down for our team to review. First, when did this accident happen?" },
  { role: "caller", t: 101.4, text: "It was 4th of July, around 6:00 p.m." },
  { role: "agent", t: 106.3, text: "Thank you. So that was July fourth at around six p.m. on McDowell and thirty-fifth Avenue. Did you receive any medical care after the accident, or are you experiencing any pain or injuries right now?" },
  { role: "caller", t: 127.7, text: "At the time I didn't get any medical care, I felt fine. But the next day I was really sore and my back was hurting, so I went in to get checked and found out I have a fracture on my hip. So I haven't been able to work and it's been a struggle to get around." },
  { role: "agent", t: 155.0, text: "I'm sorry you're going through that. A hip fracture is serious. Are you currently receiving treatment, or do you have upcoming appointments scheduled?" },
  { role: "caller", t: 171.4, text: "Yes, I have an appointment with a specialist on Monday at 2:00 p.m." },
  { role: "agent", t: 179.4, text: "Thank you for that detail. Before we continue, can I start with your full name?" },
  { role: "caller", t: 188.6, text: "Yes. My name is Abraham Perez." },
  { role: "agent", t: 192.9, text: "Thank you, Abraham. And what's the best callback number to reach you at?" },
  { role: "caller", t: 201.4, text: "626-735-6216." },
  { role: "agent", t: 203.9, text: "Thank you. And do you have an email address where we can reach you as well?" },
  { role: "caller", t: 212.7, text: "Yes. It is abe@icloud.com." },
  { role: "agent", t: 216.6, text: "Perfect. Now, was a police report made at the scene, or did police respond?" },
  { role: "caller", t: 225.4, text: "Yes, police responded right away and there was a police report made. I don't have it handy though." },
  { role: "agent", t: 236.5, text: "That's okay. Do you happen to remember the case number or report number?" },
  { role: "caller", t: 245.0, text: "No, I don't. I'll have to get it later." },
  { role: "agent", t: 250.2, text: "No problem at all. Were there any witnesses to the accident?" },
  { role: "caller", t: 257.5, text: "Yeah, there were two people at the bus stop who saw everything. One of the cops got their statement, and they said the other guy admitted he ran the red light." },
  { role: "agent", t: 274.8, text: "That's helpful. Do you have contact info for those witnesses, or did you take any photos of the scene or the damage?" },
  { role: "caller", t: 287.8, text: "I took photos on my phone, and the police officer got the contact info for the witnesses." },
  { role: "agent", t: 298.0, text: "Okay, that's good. So the officer has their information on file. Do you know the name of the other driver, or have their insurance information?" },
  { role: "caller", t: 313.7, text: "I just remember the name Steven Ramirez, but not his insurance." },
  { role: "agent", t: 321.3, text: "Thank you. Do you have auto insurance yourself, and have you reported this accident to your insurance company yet?" },
  { role: "caller", t: 334.1, text: "I have insurance with State Farm, and I have not reported the accident yet." },
  { role: "agent", t: 342.9, text: "Okay. Has an adjuster or anyone from State Farm contacted you about the accident?" },
  { role: "caller", t: 352.3, text: "No, no one has contacted me." },
  { role: "agent", t: 356.4, text: "Understood. Abraham, have you already spoken with or hired another lawyer about this accident?" },
  { role: "caller", t: 367.1, text: "No, I'm looking for one, so I haven't." },
  { role: "agent", t: 372.2, text: "Thank you. Let me recap the key facts. You were driving west on McDowell near thirty-fifth Avenue on July fourth around six p.m. when a driver named Steven Ramirez ran a red light and hit your vehicle on the driver's side. The next day you discovered a hip fracture, and you have a specialist appointment Monday at two p.m. Police made a report, two witnesses saw everything, you have photos, you have State Farm insurance but haven't reported it, and you haven't hired another attorney. Anything I missed?" },
  { role: "caller", t: 424.7, text: "No, I think you got it all." },
  { role: "agent", t: 428.7, text: "Thank you, Abraham. This information is for staff review, and any follow-up is determined by the firm. Is there anything else you'd like me to note?" },
  { role: "caller", t: 444.9, text: "Do you know how much they charge?" },
  { role: "agent", t: 449.4, text: "I understand wanting to know cost up front. I can collect information for review, but any fee arrangement would need to be explained and agreed to by the firm in writing. Anything else I can clarify?" },
  { role: "caller", t: 470.8, text: "No, that's it. Thank you." },
  { role: "agent", t: 474.6, text: "You're welcome, Abraham. Thank you for calling Sonoran Justice Injury Law, and I hope your specialist appointment on Monday goes well. Take care." },
];
