import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight } from "lucide-react";
import { constructMetadata } from "@/lib/seo";

const url = "https://abemedia.online/en/guides/dispatch-software-real-exceptions";

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  return constructMetadata({ title: "Why Dispatch Software Fails When It Ignores Real Exceptions | Abe Perez", description: "Lessons from 17 years at Waste Management: design blocked stops, access problems, contamination, overweight containers, wrong locations, and escalation into the operating model.", path: "/guides/dispatch-software-real-exceptions", locale, hasSpanishEquivalent: false, noIndex: locale !== "en" });
}

export default async function DispatchExceptionsGuide({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  if (locale !== "en") notFound();
  const schema = { "@context": "https://schema.org", "@type": "Article", "@id": `${url}#article`, headline: "Why dispatch software fails when it ignores real exceptions", description: "Operational design lessons from 17 years at Waste Management.", datePublished: "2026-08-06", dateModified: "2026-08-06", author: { "@type": "Person", "@id": "https://abemedia.online/en/about/abe-perez#person", name: "Abe Perez" }, publisher: { "@id": "https://abemedia.online/#organization" }, about: ["Dispatch software", "Waste management operations", "Operational exceptions"] };
  return (
    <article className="min-h-screen bg-background text-foreground">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} />
      <header className="border-b border-border px-6 py-16 md:py-24"><div className="mx-auto max-w-4xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Field guide · By Abe Perez</p><h1 className="mt-5 text-4xl font-medium tracking-[-0.035em] md:text-6xl">Why dispatch software fails when it ignores real exceptions</h1><p className="mt-7 text-lg leading-8 text-muted-foreground">A clean route on a screen is the easy part. The value of a dispatch system appears when the stop is blocked, the gate is locked, the container is contaminated, the weight is wrong, or the location does not match the work order.</p><div className="mt-6 flex gap-3 text-sm text-muted-foreground"><span>Published August 6, 2026</span><span aria-hidden="true">·</span><span>8-minute read</span></div></div></header>
      <div className="mx-auto grid max-w-6xl gap-12 px-6 py-16 lg:grid-cols-[0.65fr_1.35fr]">
        <aside className="lg:sticky lg:top-24 lg:self-start"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-primary">Author context</p><p className="mt-4 leading-7 text-muted-foreground">I spent 17 years at Waste Management, including Southern California dispatch leadership during recycLA. My organization supported 300+ vehicles, and I managed 27 direct reports. This article describes lessons from that prior work and does not imply a current affiliation.</p><Link href="/en/about/abe-perez" className="mt-5 inline-flex items-center gap-2 font-semibold text-primary">About Abe Perez <ArrowRight className="h-4 w-4" /></Link></aside>
        <div className="space-y-12 text-lg leading-8">
          <section><h2 className="text-3xl font-medium tracking-[-0.025em]">The happy path is not the operation</h2><p className="mt-5 text-muted-foreground">A basic dispatch screen assumes a job is assigned, the driver arrives, service happens, and the job closes. Real operations spend much of the day resolving the distance between those states. When software offers only “complete” or “not complete,” dispatchers move the real work into calls, texts, notes, and memory.</p><p className="mt-4 text-muted-foreground">That hidden process makes the dashboard look clean while the operation becomes impossible to audit.</p></section>
          <section><h2 className="text-3xl font-medium tracking-[-0.025em]">An exception needs more than a note</h2><p className="mt-5 text-muted-foreground">A useful exception record answers four questions: What prevented the work? What evidence supports that status? Who owns the next action? What must happen before the stop can return to the route?</p><div className="mt-7 grid gap-4 sm:grid-cols-2">{[{ t: "Locked gate", b: "Capture access evidence, contact attempts, the responsible party, and the approved reservice path." }, { t: "Contamination", b: "Record the material condition, photo evidence, customer notice, and whether service can proceed under an approved rule." }, { t: "Overweight container", b: "Preserve the weight or driver observation, escalation, safety constraint, and next service decision." }, { t: "Wrong location", b: "Separate address data from the actual asset location and route correction to the team that can fix the source record." }].map((item) => <div key={item.t} className="rounded-2xl border border-border bg-card p-6"><h3 className="font-semibold">{item.t}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{item.b}</p></div>)}</div></section>
          <section><h2 className="text-3xl font-medium tracking-[-0.025em]">Design ownership into the state model</h2><p className="mt-5 text-muted-foreground">A status without an owner is only a label. Each exception should route the next action to dispatch, a driver, customer service, sales, maintenance, or management. The system should show when ownership changes and why.</p><p className="mt-4 text-muted-foreground">This is also where automation needs restraint. A system can notify the customer, open a task, or schedule an approved follow-up. It should not invent the resolution when the operating policy requires a person.</p></section>
          <section><h2 className="text-3xl font-medium tracking-[-0.025em]">Capture evidence at the moment of work</h2><p className="mt-5 text-muted-foreground">End-of-day reporting becomes expensive when the facts live in separate conversations. Drivers need a fast way to attach the relevant photo, location, note, or confirmation while they are still at the stop. Dispatch needs to see that evidence without asking the driver to repeat the story.</p><p className="mt-4 text-muted-foreground">The interface should request only what the exception needs. A long generic form encourages rushed or meaningless entries.</p></section>
          <section><h2 className="text-3xl font-medium tracking-[-0.025em]">Test scenarios, not screens</h2><p className="mt-5 text-muted-foreground">A polished dispatch board can pass a product demo and fail the first real morning. Pilot testing should start with scenarios: a stop is blocked, the driver has poor service, two people update the same job, the customer disputes the status, an integration times out, and dispatch changes the route after work begins.</p><p className="mt-4 text-muted-foreground">For each scenario, verify the state, owner, evidence, notification, retry behavior, and recovery path. If the team has to explain the result outside the system, the workflow is not finished.</p></section>
          <section className="rounded-3xl bg-neutral-950 p-8 text-white"><h2 className="text-3xl font-medium">The practical build rule</h2><p className="mt-5 text-neutral-300">Do not start by copying the current spreadsheet into a nicer interface. Start with the exceptions that create calls, rework, customer escalation, and missing evidence. A smaller system that resolves one expensive handoff is more useful than a large dashboard that only displays the happy path.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/en/services/dispatch-operations-software" className="inline-flex items-center gap-2 rounded-full bg-orange-600 px-5 py-3 font-semibold">Custom dispatch systems <ArrowRight className="h-4 w-4" /></Link><Link href="/en/contact" className="inline-flex rounded-full border border-white/20 px-5 py-3 font-semibold">Discuss your workflow</Link></div></section>
        </div>
      </div>
    </article>
  );
}
